esphome:
  name: gen-fobber-transmit
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: ["custom", "custom_component"]

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  logs:
    remote_transmitter: WARN

api:

ota:
  platform: esphome

# CC1101 custom component
sensor:
  - platform: custom
    sensors:
      - id: transceiver
        internal: true
    lambda: |-
      auto my_sensor = new CC1101(
        18,    // SCK
        19,    // MISO
        23,    // MOSI
        5,     // CSN
        2,     // GDO0 (GPIO2)
        200,   // bandwidth_khz
        433.92,// frequency_mhz
        id(transmitter)
      );
      App.register_component(my_sensor);
      return {my_sensor};

# Use GDO0 on GPIO2 for both TX and RX, share SPI
remote_transmitter:
  - id: transmitter
    pin:
      number: 2
      allow_other_uses: true
    carrier_duty_percent: 100%

remote_receiver:
  - id: receiver
    pin:
      number: 2
      allow_other_uses: true
    dump:
      - raw

# Toggle switch for raw receive mode
switch:
  - platform: template
    name: "CC1101 Raw Receive"
    id: receive_mode
    optimistic: true
    turn_on_action:
      - lambda: |-
          // Enter RX mode
          get_cc1101(transceiver).endTransmission();
    turn_off_action:
      - lambda: |-
          // Exit RX mode
          get_cc1101(transceiver).beginTransmission();

# Button to trigger raw transmit 3× and disable receive mode first
button:
  - platform: template
    name: "CC1101 Transmit Raw"
    icon: mdi:send
    on_press:
      - switch.turn_off: receive_mode
      - lambda: |-
          // Enter TX mode
          get_cc1101(transceiver).beginTransmission();
      - remote_transmitter.transmit_raw:
          carrier_frequency: 433kHz
          code: [336, -1149, 1068, -407, 1084, -415, 331, -1153, 318, -1165, 1060, -429, 325, -1158, 1072, -410, 1061, -421, 1068, -431, 309, -1169, 1075, -395, 1076, -413, 1087, -395, 342, -1141, 333, -1171, 1050, -419, 324, -1171, 309, -1174, 316, -1156, 336, -1168, 316, -1164, 329, -1145, 1079, -417, 325]
          repeat:
            times: 3
            wait_time: 20ms
