# GenFobber Example - LilyGo TCAN485
# https://github.com/andrewfraley/genfobber-esphome

# TCAN485 purchase link
# https://amzn.to/4bsKyaZ

# Available Pins
# GND | VDD
# 18  | VDD
# 34  | 35
# 5   | 12
# 32  | 33
# GND | 25

esphome:
  name: genfobber-tcan485

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

api:

ota:
  platform: esphome

packages:
  genfobber:
      url: https://github.com/andrewfraley/genfobber-esphome.git
      ref: main
      refresh: 0s
      files:
        - path: 'genfober.yaml'
          vars:
            # Logger Configuration
            log_level: "INFO"  # VERBOSE / DEBUG / INFO / WARN  (note your global log level needs to be at least this same level to see these logs)
            log_tag: "genfobber"

            # CC1101 Configuration
            cc1101_frequency: "433.92MHz"

            # CC1101 Pins
            # GND                 # 1 - Black
            # VCC (+3.3V)         # 2 - Red
            cc1101_gdo0_pin: "25" # 3 - Blue
            cc1101_cs_pin: "5"    # 4 - Green
            spi_clk_pin: "12"     # 5 - Yellow
            spi_mosi_pin: "32"    # 6 - Orange
            spi_miso_pin: "33"    # 7 - Purple
            cc1101_gdo2_pin: "34" # 8 - White

            # Dry Contact Input Pin
            dry_contact_pin: "18"
            dry_contact_inverted: "true"

            # Start/Stop Generator Transmission Codes
            # these are just place holders, you should have a long set of different code timings here
            start_generator_code: "339, -1161, 339, -1161, 339, -1161, 339, -1161"
            stop_generator_code: "320, -1161, 339, -1161, 339, -1161, 339, -1161"

            # Transmission Settings
            tx_repeat_times: "3"
            tx_repeat_wait: "15ms" # This might be critical depending on the device receiving the signal, adjust if necessary
