# GenFobber Example - LilyGo T-Connect
# https://github.com/andrewfraley/genfobber-esphome

# T-Connect purchase link
# https://amzn.to/3LtYKpJ

# Available Pins
# IO2 | IO1
# IO41 | IO42
# IO39 | IO40
# IO37 | IO38
# IO35 | IO36
# IO48 | IO45
# IO21 | IO47
# IO13 | IO14
# IO11 | IO12
# GND | IO46
# GND | GND
# V3 | +5V

esphome:
  name: genfobber-tcannect

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

api:

ota:
  platform: esphome

packages:
  genfobber:
      url: https://github.com/andrewfraley/genfobber-esphome.git
      ref: main
      refresh: 0s
      files:
        - path: 'genfobber.yaml'
          vars:
            # Logger Configuration
            log_level: "INFO"  # VERBOSE / DEBUG / INFO / WARN (note your global log level needs to be at least this same level to see these logs)
            log_tag: "genfobber"

            # CC1101 Configuration
            cc1101_frequency: "433.92MHz"

            # CC1101 Pins
            # GND                 # 1 - Black
            # VCC (+3.3V)         # 2 - Red
            cc1101_gdo0_pin: "42" # 3 - Blue
            cc1101_cs_pin: "40"   # 4 - Green
            spi_clk_pin: "1"      # 5 - Yellow
            spi_mosi_pin: "13"    # 6 - Orange
            spi_miso_pin: "38"    # 7 - Purple
            cc1101_gdo2_pin: "48" # 8 - White

            # Dry Contact Input Pin
            dry_contact_pin: "11" # Grey
            dry_contact_inverted: "true"

            # Start/Stop Generator Transmission Codes
            # these are just place holders, you should have a long set of different code timings here
            start_generator_code: "339, -1161, 339, -1161, 339, -1161, 339, -1161"
            stop_generator_code: "320, -1161, 339, -1161, 339, -1161, 339, -1161"

            # Transmission Settings
            tx_repeat_times: "3"
            tx_repeat_wait: "15ms" # This might be critical depending on the device receiving the signal, adjust if necessary
